# Generated by Django 5.0.1 on 2024-01-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('1', 'To Do'), ('2', 'In Progress'), ('3', 'Done')], max_length=15),
        ),
    ]
